#ifndef SAVEANDQUIT_H
#define SAVEANDQUIT_H

/*
 *
 *	THE MODEL AND LOG FEAURE IS BY NO MEANS COMPLETE. THIS SHOULD HAVE ~100 LINES OF CODE DEDICATED TO CREATING THE FILE and about 200 LINES DEDICATED TO LOADING FROM THE FILE, THIS USES 1 FILE TO ENSURE COMPATIBILITY WITH LINUX AN WINDOWS AND SO I DONT HAVE TO GO THROUGH THE EFFORT OF WRITING SHELL SCRIPTS
 *
 * */

saveandquit(){
  FILE *frc;

  frc = fopen("", "w+");
  fprintf(frc, "%s\n", schem);
  fclose(frc);
}

#endif
